version: '3'
services:
  mongo_db:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - ./storage:/data/db
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo_db